# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $file = Get-Content pom.xml
          # Read the version with something like this:
          # $version = Select-Xml -Content $file -XPath "//version"
          # Then update the Release name:
          Write-Host "##vso[release.updatereleasename]$version"
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'wlopezob/ms-hola'
        command: 'buildAndPush'
        Dockerfile: 'dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'
        addPipelineData: false
        addBaseImageData: false
