# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      displayName: Obtener la version del ms-app
      inputs:
        targetType: 'inline'
        script: |
          [xml]$pomXml = Get-Content .\pom.xml
          # version
          Write-Host $pomXml.project.version
          $version=$pomXml.project.version
          Write-Host "##vso[task.setvariable variable=version]$version"
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'wlopezob/ms-hola'
        command: 'buildAndPush'
        Dockerfile: 'dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(version)'
        addPipelineData: false
        addBaseImageData: false
